"""add role column to users

Revision ID: 8b8e44caf851
Revises: 001_initial
Create Date: 2026-06-20 23:32:17.915010
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

"""add role column to users

Revision ID: 8b8e44caf851
Revises: 001_initial
Create Date: 2026-06-20 23:32:17.915010
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8b8e44caf851'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
